# Generated by Django 6.0.6 on 2026-06-11 06:33

import assistant.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True,
                        help_text="学校统一学号，用于身份识别",
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="学号",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="如：计算机科学与技术学院",
                        max_length=100,
                        verbose_name="院系",
                    ),
                ),
                (
                    "major",
                    models.CharField(
                        blank=True,
                        help_text="如：人工智能",
                        max_length=100,
                        verbose_name="专业",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="头像"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="个人简介"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "users",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CodeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="标题"),
                ),
                (
                    "function_type",
                    models.CharField(
                        choices=[
                            ("review", "代码审查"),
                            ("generate_test", "生成测试"),
                            ("fix", "修复 Bug"),
                        ],
                        max_length=20,
                        verbose_name="功能类型",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("java", "Java"),
                            ("cpp", "C++"),
                            ("go", "Go"),
                            ("other", "其他"),
                        ],
                        default="python",
                        max_length=20,
                        verbose_name="编程语言",
                    ),
                ),
                ("code_content", models.TextField(verbose_name="原始代码")),
                (
                    "error_info",
                    models.TextField(blank=True, default="", verbose_name="报错信息"),
                ),
                (
                    "output_content",
                    models.TextField(
                        blank=True, default="", verbose_name="AI 返回结果"
                    ),
                ),
                (
                    "token_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="消耗 Token 数"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "代码对话记录",
                "verbose_name_plural": "代码对话记录",
                "db_table": "code_histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaperHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="自动从输入截取，也可手动指定",
                        max_length=200,
                        verbose_name="标题",
                    ),
                ),
                (
                    "function_type",
                    models.CharField(
                        choices=[
                            ("polish", "润色优化"),
                            ("outline", "大纲生成"),
                            ("review", "论文点评"),
                        ],
                        max_length=20,
                        verbose_name="功能类型",
                    ),
                ),
                (
                    "input_content",
                    models.TextField(
                        help_text="用户提交的论文原文或主题描述",
                        verbose_name="输入内容",
                    ),
                ),
                (
                    "output_content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Markdown 格式的 AI 输出",
                        verbose_name="AI 返回结果",
                    ),
                ),
                (
                    "token_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="消耗 Token 数"
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="存储 polish_mode 等扩展参数",
                        verbose_name="附加参数",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "论文对话记录",
                "verbose_name_plural": "论文对话记录",
                "db_table": "paper_histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="支持 .zip .docx .pdf .py",
                        upload_to=assistant.models.upload_path,
                        verbose_name="文件",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("code_zip", "代码压缩包"),
                            ("document", "论文文档（Word/PDF）"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        help_text="保留用户上传时的文件名",
                        max_length=255,
                        verbose_name="原始文件名",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="文件大小（字节）"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="上传时间",
                    ),
                ),
                (
                    "code_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="assistant.codehistory",
                        verbose_name="关联代码记录",
                    ),
                ),
                (
                    "paper_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="assistant.paperhistory",
                        verbose_name="关联论文记录",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "上传文件",
                "verbose_name_plural": "上传文件",
                "db_table": "uploaded_files",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="codehistory",
            index=models.Index(
                fields=["user", "function_type"], name="code_histor_user_id_885d5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codehistory",
            index=models.Index(
                fields=["user", "language"], name="code_histor_user_id_116364_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codehistory",
            index=models.Index(
                fields=["user", "-created_at"], name="code_histor_user_id_93aea7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paperhistory",
            index=models.Index(
                fields=["user", "function_type"], name="paper_histo_user_id_f84e94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paperhistory",
            index=models.Index(
                fields=["user", "-created_at"], name="paper_histo_user_id_636deb_idx"
            ),
        ),
    ]
